/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lectorarchivos;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MGC
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
   
    //Crear variable para guardar la ruta del fichero
    private static String rutaFichero;
    private static File fichero;
    private JInternalFrame internalFrame;
    
    //Cuenta la cantidad de JInternalFrame
    public static int openFrameCount = 0;
    //Marca la posición "x" e "y"
    public static final int xOffset = 30, yOffset = 30; 
    
    
    public principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
 
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });
    }
    
    private void close(){
        if(openFrameCount!=0){
            if (JOptionPane.showConfirmDialog(rootPane, "Quedan ficheros abiertos, \n¿Seguro que quiere salir?",
                "Salir", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                System.exit(0);
        }else{
            System.exit(0);
        }
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpenFile = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPanePrincipal.setBackground(new java.awt.Color(210, 230, 230));

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItemOpenFile.setText("Abrir");
        jMenuItemOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenFileActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpenFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenFileActionPerformed
        try {
            //Aquí integraremos el código para abrir un archivo de tipo csv, xls o txt.+
            abrirSelector();
        } catch (IOException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemOpenFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }
    
    //Crear método para abrir selector
    public void abrirSelector() throws IOException{
        JFileChooser selector = new JFileChooser();
        FileNameExtensionFilter filtroArchivo=new FileNameExtensionFilter("csv & xls & txt","csv","xls","txt");
        selector.setFileFilter(filtroArchivo);
        selector.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if(!selector.isMultiSelectionEnabled()){
            selector.setMultiSelectionEnabled(true);
        }
        
        int r=selector.showOpenDialog(this);
        
        
        if(r==JFileChooser.APPROVE_OPTION){
            //Recorremos el array de ficheros seleccionados
            for(int i=0;i<selector.getSelectedFiles().length;i++){
                rutaFichero = selector.getSelectedFiles()[i].toPath().toAbsolutePath().toString();
                fichero = selector.getSelectedFiles()[i];
                
                openFrameCount += 1;

                System.out.println("Ruta del fichero --> "+rutaFichero);

                //Ahora averiguaremos que extension es
                /*** 
                 Para ello llamaremos al método getExtension
                 Como devuelve un String lo meteremos dentro
                 de una variable de tipo String
                 ***/

                //Creación de la ventana interna
                makeInternal(fichero);
            }
            
            
        }else{
            System.out.println("Yo devuelvo nullo");
        }
        
      
        
    }
    
   
    //Crear método para recoger la extensión del fichero
    public static String getExtension(File fichero){
        String fileName = fichero.getName().toString();
        int index = fileName.lastIndexOf('.');
        if(index == -1){
            return "";
        }else{
            return fileName.substring(index + 1);
        }
    }
    
    //Crear ventana interna
    public void makeInternal(File archivo) throws IOException{
        String titulo = null;
        boolean csv = false;
        String recogerExtension = getExtension(fichero);
        if(recogerExtension.equals("xls")){
            titulo = "XLS - "+fichero.getName().toString();
            csv = false;
        }else if(recogerExtension.equals("csv")){
            titulo = "CSV - "+fichero.getName().toString();
            csv = true;
        }
        internalFrame = new JInternalFrame(titulo,true,true,true,true);
        internalFrame.setBounds(100,100,600,400);
        
        
        jDesktopPanePrincipal.add(internalFrame);
        //internalFrame.getContentPane().setLocation(200, sumaLoc+=1000);
        internalFrame.show();
        
        if(csv){
            //Crear JPanel enviandole la ruta del archivo
            VerCSV csvFichero = new VerCSV(fichero);
            
            //Cambiar localizacion del frame interno
            
            internalFrame.setLocation(xOffset*openFrameCount, yOffset*openFrameCount);
            
            //Añadimos el JPanel a internalframe
            internalFrame.add(csvFichero);
            
            //mostrar el jpanel
            csvFichero.setVisible(true);
        }else{
            
        }
        //Insertar un JPanel dentro de internalFrame
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemOpenFile;
    // End of variables declaration//GEN-END:variables
}
