/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lectorarchivos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MGC
 */
public class VerCSV extends javax.swing.JPanel {
    File fichero = null;
    
    /**
     * Creates new form VerCSV
     */
    public VerCSV(File fichero) throws IOException {
        initComponents();
        this.fichero = fichero;
        jLabelRutaFichero.setText(fichero.getAbsolutePath().toString());
        
        //LLamamos al metodo para llenar la tabla
        /*
            Tendremos que pasarle la tabla y el la ruta
            del fichero
        */
        llenarTabla(jTableInfoCSV,fichero);
        
        
    }
    
    public static void llenarTabla(JTable tabla, File fichero) throws FileNotFoundException, IOException{
        //Almacenamos la direccion donde se encuenta el fichero en un String
        String rutaFichero = fichero.getAbsolutePath().toString();
        BufferedReader br = null;
        String line = "";
        //Asignar un separador
        String csvSplitBy = ";";
        
        //Realizar lectura del fichero para coger los titulos
        String  titulos [] = new String[4];
   
        br = new BufferedReader(new FileReader(rutaFichero));
        
        //Empieza la lectura
        while((line = br.readLine()) != null){
            String[] cabecera = line.split(csvSplitBy);
            if(cabecera[0].equals("Pozo")
                && cabecera[1].equals("Localizacion")
                && cabecera[2].equals("Litros")
                && cabecera[3].equals("Fecha")){
                
                titulos[0] = cabecera[0];
                titulos[1] = cabecera[1];
                titulos[2] = cabecera[2];
                titulos[3] = cabecera[3];
            }
            
        }
        
        //Volver a los valores iniciales
        line = "";
        br = null;
        
        
        String fila[] = new String[4];
        
        DefaultTableModel model = new DefaultTableModel(null,titulos);
        
        
        try{
            br = new BufferedReader(new FileReader(rutaFichero));
            
            //Empieza la lectura del csv
            while((line = br.readLine())!=null){
                //Usar el ';' como separador
                String[] datos = line.split(csvSplitBy);
                
                /*
                    Una vez tengamos los datos almacenados
                    en el array toca almacenarlos en la tabla
                */
                
                fila[0] = datos[0];
                fila[1] = datos[1];
                fila[2] = datos[2];
                fila[3] = datos[3];
                
                //Realizamos la comprobación de que las filas no se igual a lo especificado...
                if(!fila[0].equals("Pozo") && !fila[1].equals("Localizacion") && !fila[2].equals("Litros")){
                    model.addRow(fila);
                }
            }
            tabla.setModel(model);
        }catch(IOException e){
            e.printStackTrace();
        }finally{
            if(br!=null){
                try{
                    br.close();
                }catch(IOException e){
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRutaFichero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInfoCSV = new javax.swing.JTable();

        jLabelRutaFichero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelRutaFichero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRutaFichero.setText("Ruta del fichero");

        jTableInfoCSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CONTADOR", "LOCALIZACIÓN", "LITROS"
            }
        ));
        jScrollPane1.setViewportView(jTableInfoCSV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabelRutaFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelRutaFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel jLabelRutaFichero;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTableInfoCSV;
    // End of variables declaration//GEN-END:variables

}
